sudo: false
services:
  - docker
language: bash
before_install:
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_7f62a8cdc221_key -iv $encrypted_7f62a8cdc221_iv -in ${TRAVIS_BUILD_DIR}/travis/mongo-k8s-sidecar-deploykey.enc -out ~/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa
  - ssh-add ~/.ssh/travis_rsa
install:
  - ${TRAVIS_BUILD_DIR}/travis/releaseVersioning.sh
script:
  - ${TRAVIS_BUILD_DIR}/travis/build.sh
after_success:
  - ${TRAVIS_BUILD_DIR}/travis/releaseTagging.sh
#safelist
branches:
  only:
    - dev
    - master
